version: "{build}"

image: Visual Studio 2019

cache:
 - C:\gopath\pkg\mod -> go.sum
 - C:\ProgramData\chocolatey\bin -> appveyor.yml
 - C:\ProgramData\chocolatey\lib -> appveyor.yml

clone_folder: C:\gopath\src\github.com\influxdata\telegraf

environment:
  GOPATH: C:\gopath

stack: go 1.15

platform: x64

install:
  - choco install make
  - dir C:\msys64\
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | c:\msys64\bash -s v1.34.1
  - git config --system core.longpaths true
  - go version
  - go env

build_script:
  - make deps
  - make telegraf

test_script:
  - make check
  - make test-windows

artifacts:
  - path: telegraf.exe
